---
- name: compute_attribute
  theforeman.foreman.compute_attribute:
    compute_profile: "{{ loop_compute_attribute.compute_profile }}"
    compute_resource: "{{ loop_compute_attribute.compute_resource }}"
    password: "{{ tp_foreman_configure_password }}"
    server_url: "{{ tp_foreman_configure_server_url }}"
    state: "{{ loop_auth_source_ldap.state | default(omit) }}"
    username: "{{ tp_foreman_configure_user }}"
    validate_certs: "{{ tp_foreman_configure_validate_certs | default('yes') }}"
    vm_attrs: "{{ loop_compute_attribute.vm_attrs | default(omit) }}"
  loop: "{{ tp_foreman_configure_compute_attributes }}"
  loop_control:
    loop_var: loop_compute_attribute
    label: "{{ loop_compute_attribute.compute_profile }} - {{ loop_compute_attribute.resource }}"
  tags:
    - compute_attribute
    - compute_profile
    - host
    - hostgroup
