---
- name: content_credential
  theforeman.foreman.content_credential:
    content: "{{ loop_content_credential.content }}"
    content_type: "{{ loop_content_credential.content_type }}"
    name: "{{ loop_content_credential.name }}"
    organization: "{{ loop_content_credential.organization }}"
    password: "{{ tp_foreman_configure_password }}"
    server_url: "{{ tp_foreman_configure_server_url }}"
    state: "{{ loop_auth_source_ldap.state | default(omit) }}"
    username: "{{ tp_foreman_configure_user }}"
    validate_certs: "{{ tp_foreman_configure_validate_certs | default('yes') }}"
  loop: "{{ tp_foreman_configure_content_credentials }}"
  loop_control:
    loop_var: loop_content_credential
    label: "{{ loop_content_credential.name }}"
  tags:
    - content_credential
