---
- name: content_upload
  theforeman.foreman.content_upload:
    organization: "{{ loop_content_upload.organization }}"
    password: "{{ tp_foreman_configure_password }}"
    product: "{{ loop_content_upload.product }}"
    repository: "{{ loop_content_upload.repository }}"
    server_url: "{{ tp_foreman_configure_server_url }}"
    src: "{{ loop_content_upload.src }}"
    state: "{{ loop_auth_source_ldap.state | default(omit) }}"
    username: "{{ tp_foreman_configure_user }}"
    validate_certs: "{{ tp_foreman_configure_validate_certs | default('yes') }}"
  loop: "{{ tp_foreman_configure_content_uploads }}"
  loop_control:
    loop_var: loop_content_upload
    label: "{{ loop_content_upload.product }} [{{ loop_content_upload.repository }}]"
  tags:
    - content_upload
