---
# https://theforeman.github.io/foreman-ansible-modules/v1.2.0/plugins/organization_module.html#ansible-collections-theforeman-foreman-organization-module
- name: organization
  theforeman.foreman.organization:
    description: "{{ loop_organization.description | default(omit) }}"
    label: "{{ loop_organization.label | default(omit) }}"
    name: "{{ loop_organization.name }}"
    parameters: "{{ loop_organization.parameters | default(omit) }}"
    password: "{{ tp_foreman_configure_password }}"
    server_url: "{{ tp_foreman_configure_server_url }}"
    state: "{{ loop_auth_source_ldap.state | default(omit) }}"
    username: "{{ tp_foreman_configure_user }}"
    validate_certs: "{{ tp_foreman_configure_validate_certs | default('yes') }}"
  loop: "{{ tp_foreman_configure_organizations }}"
  loop_control:
    loop_var: loop_organization
    label: "{{ loop_organization.name }}"
  tags:
    - always
    - organization
