---
# https://theforeman.github.io/foreman-ansible-modules/v1.2.0/plugins/repository_module.html#ansible-collections-theforeman-foreman-repository-module
- name: repository
  theforeman.foreman.repository:
    ansible_collection_requirements: "{{ loop_repository.ansible_collection_requirements | default(omit) }}"
    auto_enabled: "{{ loop_repository.auto_enabled | default(omit) }}"
    checksum_type: "{{ loop_repository.checksum_type | default(omit) }}"
    content_type: "{{ loop_repository.content_type }}"
    deb_architectures: "{{ loop_repository.deb_architectures | default(omit) }}"
    deb_components: "{{ loop_repository.deb_components | default(omit) }}"
    deb_errata_url: "{{ loop_repository.deb_errata_url | default(omit) }}"
    deb_releases: "{{ loop_repository.deb_releases | default(omit) }}"
    description: "{{ loop_repository.description | default(omit) }}"
    docker_tags_whitelist: "{{ loop_repository.docker_tags_whitelist | default(omit) }}"
    docker_upstream_name: "{{ loop_repository.docker_upstream_name | default(omit) }}"
    download_policy: "{{ loop_repository.download_policy | default(omit) }}"
    gpg_key: "{{ loop_repository.gpg_key | default(omit) }}"
    http_proxy: "{{ loop_repository.http_proxy | default(omit) }}"
    http_proxy_policy: "{{ loop_repository.http_proxy_policy | default(omit) }}"
    ignorable_content: "{{ loop_repository.ignorable_content | default(omit) }}"
    ignore_global_proxy: "{{ loop_repository.ignore_global_proxy | default(omit) }}"
    label: "{{ loop_repository.label | default(omit) }}"
    mirror_on_sync: "{{ loop_repository.mirror_on_sync | default(omit) }}"
    name: "{{ loop_repository.name }}"
    organization: "{{ loop_repository.organization }}"
    password: "{{ tp_foreman_configure_password }}"
    product: "{{ loop_repository.product }}"
    server_url: "{{ tp_foreman_configure_server_url }}"
    ssl_ca_cert: "{{ loop_repository.ssl_ca_cert | default(omit) }}"
    ssl_client_cert: "{{ loop_repository.ssl_client_cert | default(omit) }}"
    ssl_client_key: "{{ loop_repository.ssl_client_key | default(omit) }}"
    state: "{{ loop_auth_source_ldap.state | default(omit) }}"
    unprotected: "{{ loop_repository.unprotected | default(omit) }}"
    upstream_password: "{{ loop_repository.upstream_password | default(omit) }}"
    upstream_username: "{{ loop_repository.upstream_username | default(omit) }}"
    url: "{{ loop_repository.url | default(omit) }}"
    username: "{{ tp_foreman_configure_user }}"
    validate_certs: "{{ tp_foreman_configure_validate_certs | default('yes') }}"
    verify_ssl_on_sync: "{{ loop_repository.verify_ssl_on_sync | default(omit) }}"
  loop: "{{ tp_foreman_configure_repositorys }}"
  loop_control:
    loop_var: loop_repository
    label: "{{ loop_repository.name }} [{{ loop_repository.product }} / {{ loop_repository.content_type }}]"
  tags:
    - repository
    - content_upload
    - content_view_filter
    - repository_set
    - repository_sync
