---
# https://theforeman.github.io/foreman-ansible-modules/v1.2.0/plugins/scc_product_module.html#ansible-collections-theforeman-foreman-scc-product-module
- name: scc_product
  theforeman.foreman.scc_product:
    organization: "{{ loop_scc_product.organization }}"
    password: "{{ tp_foreman_configure_password }}"
    scc_account: "{{ loop_scc_product.scc_account }}"
    scc_product: "{{ loop_scc_product.scc_product }}"
    server_url: "{{ tp_foreman_configure_server_url }}"
    state: "{{ loop_auth_source_ldap.state | default(omit) }}"
    username: "{{ tp_foreman_configure_user }}"
    validate_certs: "{{ tp_foreman_configure_validate_certs | default('yes') }}"
  loop: "{{ tp_foreman_configure_scc_products }}"
  loop_control:
    loop_var: loop_scc_product
    label: "{{ loop_scc_product.scc_product }} [{{ loop_scc_product.account }}]"
  tags:
    - scc_product
